In [78]:
import numpy as np
import cv2 as cv

In [79]:
cameraIntrinsic = np.mat(
    [
        [729.2205288939331, 0.0, 484.20682264918315],
        [0.0, 728.0294742172647, 324.54740828467595],
        [0.0, 0.0, 1.0]
    ]
)
cameraDistort = np.mat(
    [-0.3580226107916401, 3.1574617019213114, 0.02323167066358097, -0.013430391090519293, -8.016922034682826]
)

In [80]:
cameraIntrinsic

matrix([[729.22052889,   0.        , 484.20682265],
        [  0.        , 728.02947422, 324.54740828],
        [  0.        ,   0.        ,   1.        ]])

In [81]:
uv_new = cv.undistortPoints(np.array([[[500.0, 600.0]]]), cameraIntrinsic, cameraDistort, P=cameraIntrinsic)
uv_new = np.concatenate((uv_new.reshape(2,1), [[1]]), axis=0)
uv_new

array([[501.25634566],
       [595.89769468],
       [  1.        ]])

In [82]:
normCameraCoordinates = np.matmul(np.linalg.inv(cameraIntrinsic), uv_new)
normCameraCoordinates

matrix([[0.02338048],
        [0.37271882],
        [1.        ]])

In [83]:
differential_height = 1.0
scaling_factor = differential_height / float(normCameraCoordinates[1])
scaling_factor

2.6829876758002498

In [98]:
def returnRotMatrix(radians):
    rotMatrix = np.array(
        [
            [1, 0, 0],
            [0, np.cos(radians), -np.sin(radians)],
            [0, np.sin(radians), np.cos(radians)]
        ]
    )
    return rotMatrix
tvec = np.matmul(np.linalg.inv(returnRotMatrix(0.1 * 3.1415926)), normCameraCoordinates) * scaling_factor
tvec

matrix([[0.06272953],
        [1.78014529],
        [2.24265593]])

In [88]:
print("Final Translation: X %.5fm, Y %.5fm" % (float(tvec[2][0]), float(tvec[1][0])))

Final Translation: X 2.24266m, Y 1.78015m
